---
- name: Install and configure zsh
  hosts: all
  become: yes

  vars:
    users:
      - name: rokd
        home: /home/rokd
      - name: root
        home: /root

  tasks:

    - name: Install zsh using package manager
      package:
        name: zsh
        state: present

    - name: Install util-linux-user on RHEL-based systems
      dnf:
        name: "util-linux-user,git,tar"
        state: present
      when: "'RedHat' in ansible_distribution or 'Rocky' in ansible_distribution or 'AlmaLinux' in ansible_distribution"


    - name: Modify /etc/pam.d/chsh for unrestricted chsh
      lineinfile:
        path: /etc/pam.d/chsh
        regexp: '^auth\s+required\s+pam_shells.so'
        line: 'auth sufficient pam_shells.so'
        state: present
        backup: yes

    - name: Change shell for users
      command: chsh -s /usr/bin/zsh {{ item.name }}
      loop: "{{ users }}"

    - name: Check if .oh-my-zsh exists
      stat:
        path: ~/.oh-my-zsh
      register: oh_my_zsh_stat

    - name: Install .oh-my-zsh
      become_user: "{{ item.name }}"
      shell: "curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | /bin/sh"
      loop: "{{ users }}"
      when: not oh_my_zsh_stat.stat.exists

    - name: Clone powerlevel10k theme for users
      git:
        repo: "https://github.com/romkatv/powerlevel10k.git"
        dest: "{{ item.home }}/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1
      loop: "{{ users }}"

    - name: Clone zsh-autosuggestions plugin
      git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
        dest: "{{ item.home }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      loop: "{{ users }}"

    - name: Clone zsh-syntax-highlighting plugin
      git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "{{ item.home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      loop: "{{ users }}"

    - name: Copy zshrc file
      copy:
        src: "files/zshrc"
        dest: "{{ item.home }}/.zshrc"
      loop: "{{ users }}"

    - name: Copy p10k.zsh file
      copy:
        src: "files/p10k.zsh"
        dest: "{{ item.home }}/.p10k.zsh"
      loop: "{{ users }}"





